website/__init__.py
from flask import Flask  # Importing the Flask class from the Flask framework
from . import data_sync
import threading
def run_data_sync():
    """
        Function to run the data synchronization process.

        This function initiates the data synchronization process defined in the data_sync module.
    """
    data_sync.data_synchronization()


def create_app():
    """
    Creates and configures a Flask application instance.

    This function initializes a Flask application, registers blueprints,
    and returns the configured application instance.

    Returns:
        Flask: The configured Flask application instance.
    """
    app = Flask(__name__)  # Creating a Flask application instance

    # Importing views module and registering the blueprint
    from .views import views
    app.register_blueprint(views, url_prefix='/')

    return app  # Returning the configured Flask application instance

website/views.py
from flask import Blueprint, render_template, request
from . import dbmodels, datacleansing

# Creating a Blueprint named 'views'
views = Blueprint("views", __name__)

# Accessing the MongoDB collection through the Database class
collection = dbmodels.Database().cve_collection


@views.route('/')
def index():
    """
    Renders the CVE list page.

    Retrieves CVE data from the database, applies pagination, and renders the CVE list template.

    Returns:
        str: Rendered HTML template for the CVE list page.
    """
    # Retrieving page number and items per page from the request query parameters
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 10, type=int)

    # Counting total number of CVE records in the database
    total_count = collection.count_documents({})

    # Retrieving CVE data from the database with pagination
    data = list(collection.find().skip((page - 1) * per_page).limit(per_page))

    # Transforming data to required format for rendering
    cve_list = []
    for document in data:
        cve_list.append({
            "id": document["id"],
            "sourceIdentifier": document["sourceIdentifier"],
            "published": datacleansing.date_format_changer(document["published"]),
            "lastModified": datacleansing.date_format_changer(document["lastModified"]),
            "vulnStatus": document["vulnStatus"]
        })

    # Rendering the CVE list template with the transformed data
    return render_template('index.html', cve_list=cve_list, page=page, per_page=per_page, total_count=total_count)


@views.route('/cve/<cve_id>')
def cve_details(cve_id):
    """
    Renders the CVE details page for a specific CVE ID.

    Retrieves CVE details from the database based on the provided CVE ID and renders the CVE details template.

    Args:
        cve_id (str): The ID of the CVE.

    Returns:
        str: Rendered HTML template for the CVE details page.
    """
    # Retrieving CVE details from the database based on the provided CVE ID
    cve = collection.find_one({"id": cve_id})

    # If CVE details exist, render the CVE details template with the data
    if cve:
        # Extracting English description from the CVE details
        english_description = next((desc['value'] for desc in cve['descriptions'] if desc['lang'] == 'en'), None)

        # Extracting CVSS metrics from the CVE details
        cvss_metrics = cve["metrics"].get("cvssMetricV2", [{}])[0]
        cvss_data = cvss_metrics.get("cvssData", {})

        # Extracting other relevant CVE details for rendering
        severity = cvss_metrics.get("baseSeverity", "")
        baseScore = cvss_data.get("baseScore", 0)
        accessVector = cvss_data.get("accessVector", "")
        accessComplexity = cvss_data.get("accessComplexity", "")
        authentication = cvss_data.get("authentication", "")
        confidentialityImpact = cvss_data.get("confidentialityImpact", "")
        integrityImpact = cvss_data.get("integrityImpact", "")
        availabilityImpact = cvss_data.get("availabilityImpact", "")
        vectorString = cvss_data.get("vectorString", "")
        impactScore = cvss_metrics.get("impactScore", 0)
        exploitabilityScore = cvss_metrics.get("exploitabilityScore", 0)

        # Extracting CPE details from the CVE details
        configurations = cve.get("configurations", [])
        cpe = []
        for configuration in configurations:
            nodes = configuration.get("nodes", [])
            for node in nodes:
                cpe_match = node.get("cpeMatch", [])
                for item in cpe_match:
                    cpe.append({
                        "criteria": item.get("criteria", ""),
                        "matchCriteriaId": item.get("matchCriteriaId", ""),
                        "vulnerable": item.get("vulnerable", False)
                    })

        # Rendering the CVE details template with the extracted data
        return render_template('cve_details.html', cve={
            "id": cve["id"],
            "descriptions": english_description,
            "severity": severity,
            "baseScore": baseScore,
            "accessVector": accessVector,
            "accessComplexity": accessComplexity,
            "authentication": authentication,
            "confidentialityImpact": confidentialityImpact,
            "integrityImpact": integrityImpact,
            "availabilityImpact": availabilityImpact,
            "impactScore": impactScore,
            "exploitabilityScore": exploitabilityScore,
            "vectorString": vectorString,
            "cpe": cpe
        })

website/templates/cve_details.html
<!DOCTYPE html>
<html>
<head>
    <title>CVE Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        h3 {
            margin-top: 30px;
        }
        p {
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ cve.id }}</h1>
        <h3>Description</h3>
        <p>{{ cve.descriptions }}</p>
        <h3>CVSS V2 METRICS</h3>
        <p><b>Severity: </b>{{ cve.severity }}</p>
        <p><b>Vector String: </b>{{ cve.vectorString }}</p>
        <p><b>Score: </b>{{ cve.baseScore }}</p>

        <table>
            <thead>
                <tr>
                    <th>Access Vector</th>
                    <th>Access Complexity</th>
                    <th>Authentication</th>
                    <th>Confidentiality Impact</th>
                    <th>Integrity Impact</th>
                    <th>Availability Impact</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ cve.accessVector }}</td>
                    <td>{{ cve.accessComplexity }}</td>
                    <td>{{ cve.authentication }}</td>
                    <td>{{ cve.confidentialityImpact }}</td>
                    <td>{{ cve.integrityImpact }}</td>
                    <td>{{ cve.availabilityImpact }}</td>
                </tr>
            </tbody>
        </table>
        <h3>Scores:</h3>
        <p>Exploitability Score: {{ cve.exploitabilityScore }}</p>
        <p>Impact Score: {{ cve.impactScore }}</p>
        <h3>CPE:</h3>
        <table>
            <thead>
                <tr>
                    <th>Criteria</th>
                    <th>Match Criteria ID</th>
                    <th>Vulnerable</th>
                </tr>
            </thead>
            <tbody>
                {% for cpe_item in cve.cpe %}
                <tr>
                    <td>{{ cpe_item.criteria }}</td>
                    <td>{{ cpe_item.matchCriteriaId }}</td>
                    <td>{{ cpe_item.vulnerable }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

website/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>CVE List</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <style>
        /* CSS styles for the CVE list page */
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 1000px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            text-align: left;
        }
        p {
            color: #555;
            text-align: left;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #f9f9f9;
            cursor: pointer;
        }
        .pagination {
            display: flex;
            justify-content: flex-end;
            margin-top: 20px;
        }
        .pagination a {
            color: black;
            padding: 8px 16px;
            text-decoration: none;
            transition: background-color .3s;
        }
        .pagination a.active {
            background-color: #4CAF50;
            color: white;
        }
        .pagination a:hover:not(.active) {
            background-color: #ddd;
        }
        .per-page-options {
            display: flex;
            justify-content: flex-start;
            margin-bottom: 20px;
        }
        .res {
            margin-top: 20px;
            margin-left: 10px;
        }
        .per-page-options select {
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 5px;
            background-color: #fff;
            color: #333;
            transition: border-color .3s;
        }
        .per-page-options select:hover {
            border-color: #aaa;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Title -->
        <h1>CVE List</h1>

        <!-- Table for CVE entries -->
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Source Identifier</th>
                    <th>Published</th>
                    <th>Last Modified</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <!-- Loop through CVE entries -->
                {% for cve in cve_list %}
                    <tr onclick="location.href='{{ url_for('views.cve_details', cve_id=cve.id) }}';">
                        <td>{{ cve.id }}</td>
                        <td>{{ cve.sourceIdentifier }}</td>
                        <td>{{ cve.published }}</td>
                        <td>{{ cve.lastModified }}</td>
                        <td>{{ cve.vulnStatus }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Display result information -->
        <div class="res">
            <b>{{ (page * 10) - 9 }}-{{ page * 10 }} of {{ total_count }} records</b>
        </div>

        <!-- Pagination controls -->
        <div class="pagination">
            {% if page > 1 %}
                <a href="{{ url_for('views.index', page=page-1, per_page=per_page) }}">&laquo; Previous</a>
            {% endif %}
            {% if page < (total_count // per_page) + 1 %}
                <a href="{{ url_for('views.index', page=page+1, per_page=per_page) }}">Next &raquo;</a>
            {% endif %}
        </div>
    </div>
</body>
</html>